### PR TITLE
Add Netlify CMS

### PR DESCRIPTION
**Pull request by gil--**
Add Netlify CMS + Basic  Configurations for various sections

### CODE REVIEW

**Comment by mdesignco** [comment]
Nice addition, have been following this repo!

Have you enabled open user signups in for this project in Netlify Identity?

**Comment by gil--** [comment]
@mdesignco Not sure I follow. Do you mean open user signups for Netlify admin on https://bodega.netlify.com/admin/ or Shopify? Currently it's set to invite only as I still need to setup proper settings for merging changes, to prevent direct commits like: https://github.com/gil--/gatsby-starter-shopifypwa/commit/fcb9bb23b1eed8c222e61dd385f146ad6db1d194 🤦‍♂️

**Comment by mdesignco** [comment]
Yes, exactly - to preview what you've added here from `https://bodega.netlify.com/admin/` 

Could simply clone and run own instance, was just curious.

**Comment by gil--** [comment]
@mdesignco Ah got it. I'll add demo site with open-admin to the Todo-List. I'll spin one up this weekend on a master-demo branch.

**Comment by gil--** [comment]
@mdesignco Still looking into a more format demo setup but I'm working on getting a sandbox version to work with CodeSandbox, see https://codesandbox.io/s/98rxxwxj1w in the browser view, go to /admin/ and it will load netlify cms without any auth. Going to get this up on something like  [sandbox.bodega.cloud](sandbox.bodega.cloud) now that we have [demo.bodega.cloud](demo.bodega.cloud)

[Edit gatsby-starter-shopify](https://codesandbox.io/s/98rxxwxj1w)

**Pull request merged**
